//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORPortal_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actual
    {
        public int SlNo { get; set; }
        public Nullable<int> Actual1 { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> Machine_Id { get; set; }
    }
}
