//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORPortal_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Break
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<int> Shift_Id { get; set; }
        public Nullable<int> Machine_Id { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
