//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORPortal_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public int SlNo { get; set; }
        public int Machine_ID { get; set; }
        public int ID { get; set; }
        public string Parameters { get; set; }
        public Nullable<System.DateTime> ExecutionTimestamp { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
