//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORPortal_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonProblem
    {
        public string Description { get; set; }
        public int Code { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> SubType { get; set; }
    }
}
