//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORPortal_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineInput
    {
        public int Id { get; set; }
        public int Machine_Id { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<int> Valid { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
