//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORPortal_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Machine()
        {
            this.Breaks = new HashSet<Break>();
            this.MachineInputs = new HashSet<MachineInput>();
            this.ProjectMachines = new HashSet<ProjectMachine>();
            this.Sessions = new HashSet<Session>();
            this.ShiftMachines = new HashSet<ShiftMachine>();
            this.SpecificProblems = new HashSet<SpecificProblem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double TOS { get; set; }
        public int Pulses { get; set; }
        public int Pieces { get; set; }
        public double Rmin { get; set; }
        public double Rmax { get; set; }
        public double Omin { get; set; }
        public double Omax { get; set; }
        public double Gmin { get; set; }
        public double Gmax { get; set; }
        public Nullable<int> MachineGroupId { get; set; }
        public Nullable<double> MPDuration { get; set; }
        public Nullable<double> StopCloseDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Break> Breaks { get; set; }
        public virtual MachineGroup MachineGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineInput> MachineInputs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMachine> ProjectMachines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftMachine> ShiftMachines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificProblem> SpecificProblems { get; set; }
    }
}
