//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORPortal_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMachine
    {
        public int Id { get; set; }
        public int Project_Id { get; set; }
        public int Machine_Id { get; set; }
        public string Active { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Project Project { get; set; }
    }
}
