//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORPortal_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTracker
    {
        public int SlNo { get; set; }
        public Nullable<int> Machine_Id { get; set; }
        public Nullable<int> Shift_Id { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public Nullable<int> SessionActual { get; set; }
        public Nullable<int> SessionPlan { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
    }
}
